/// The Flutter test that runtime capture writes into the app (under
/// `.dart_tool/flutter2figma/`) and runs with `flutter test`.
///
/// It starts the app through its own `main()`, so dependency injection,
/// providers and themes are set up as in the real app. Then it pushes each
/// screen onto the app's root navigator and records what Flutter rendered:
/// a tree of boxes, text, icons and images with their exact positions.
/// Anything painted by a `CustomPainter` (switches, checkboxes, charts, ...)
/// is rasterized by calling the painter, and unknown leaf render objects are
/// cropped from a screenshot, so every widget comes out as it looks.
///
/// Placeholders replaced by [harnessSource]:
/// - `/*IMPORTS*/`: the app's `main.dart` as `app`, screen libraries as `s0`…
/// - `/*SCREENS*/`: `'Name': () => s0.Name(),` entries.
/// - `/*BUILD*/`: how a screen is built, from `name` and `fallback`.
library;

/// The test file for the given imports and screen builders.
///
/// [setupImports] and [setup] run before the app starts (plugin fakes, the
/// app's own `setUp()`); [wrap] is an expression of `name` and `screen`
/// that wraps each pushed screen, e.g. with providers it expects.
String harnessSource({
  required String mainImport,
  required Map<String, String> screenImports,
  required Map<String, String> screens,
  List<String> setupImports = const [],
  List<String> setup = const [],
  String wrap = 'screen',
  String build = 'fallback()',
  bool nested = false,
}) {
  final imports = [
    "import '$mainImport' as app;",
    for (final MapEntry(:key, :value) in screenImports.entries)
      "import '$key' as $value;",
    ...setupImports,
    if (nested) "import 'package:nested/nested.dart' as nested;",
  ].join('\n');
  final builders = [
    for (final MapEntry(:key, :value) in screens.entries)
      "  '$key': () => $value,",
  ].join('\n');
  return _template
      .replaceFirst('/*IMPORTS*/', imports)
      .replaceFirst('/*SCREENS*/', builders)
      .replaceFirst('/*SETUP*/', setup.join('\n'))
      .replaceFirst('/*WRAP*/', wrap)
      .replaceFirst('/*BUILD*/', build)
      .replaceFirst('/*PROVIDERS*/', nested ? _nestedProviders : _noProviders);
}

const _noProviders = r'''
List<f.Widget> _routeProviders() => const [];

f.Widget _provide(List<f.Widget> providers, f.Widget child) => child;
''';

/// Providers (`BlocProvider`, `Provider`, ...) found on the app's initial
/// route, below the Navigator: screens pushed later get them too, since
/// apps often provide a screen's blocs in the route that shows it.
const _nestedProviders = r'''
List<f.Widget> _routeProviders() {
  final navigators = t.find.byType(f.Navigator).evaluate();
  if (navigators.isEmpty) return const [];
  final found = <f.Widget>[];
  void visit(f.Element e) {
    final widget = e.widget;
    if (widget is nested.SingleChildWidget && widget is! nested.Nested) found.add(widget);
    e.visitChildElements(visit);
  }
  navigators.first.visitChildElements(visit);
  return found;
}

f.Widget _provide(List<f.Widget> providers, f.Widget child) => providers.isEmpty
    ? child
    : nested.Nested(children: providers.cast<nested.SingleChildWidget>(), child: child);
''';

const _template = r'''
// Generated by flutter2figma (runtime capture). Safe to delete.
// ignore_for_file: type=lint, depend_on_referenced_packages
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart' as f;
import 'package:flutter/rendering.dart' as r;
import 'package:flutter/services.dart' as s;
import 'package:flutter_test/flutter_test.dart' as t;
import 'package:flutter_test/flutter_test.dart' show addTearDown;

/*IMPORTS*/

const _out = String.fromEnvironment('F2F_OUT');
const _shots = String.fromEnvironment('F2F_SCREENSHOTS');
const _flutterRoot = String.fromEnvironment('F2F_FLUTTER_ROOT');
const _width = int.fromEnvironment('F2F_WIDTH', defaultValue: 390);
const _height = int.fromEnvironment('F2F_HEIGHT', defaultValue: 844);
const _scale = 2.0;

final Map<String, f.Widget Function()> _screens = {
/*SCREENS*/
};

/// Plugin fakes and the app's own test setup, before main() runs.
Future<void> _setUp() async {
/*SETUP*/
}

f.Widget _wrap(String name, f.Widget screen) => /*WRAP*/;

f.Widget _build(String name, f.Widget Function() fallback) => /*BUILD*/;

/*PROVIDERS*/

// ---------------------------------------------------------------------------
// Fonts: real ones, so text measures as on a device.
// ---------------------------------------------------------------------------

final _loadedFamilies = <String>{};
final _robotoFiles = <Uint8List>[];

Future<void> _loadFamily(String family, Iterable<Future<ByteData>> fonts) async {
  final loader = s.FontLoader(family);
  for (final font in fonts) {
    loader.addFont(font);
  }
  await loader.load();
  _loadedFamilies.add(family);
}

Future<void> _loadFonts() async {
  final dir = Directory('$_flutterRoot/bin/cache/artifacts/material_fonts');
  if (dir.existsSync()) {
    for (final file in dir.listSync().whereType<File>()) {
      final name = file.uri.pathSegments.last;
      if (name.startsWith('Roboto-') && name.endsWith('.ttf')) {
        _robotoFiles.add(file.readAsBytesSync());
      }
    }
  }
  await _loadFamily('Roboto', _robotoFiles.map((b) => Future.value(ByteData.sublistView(b))));
  try {
    final manifest = jsonDecode(await s.rootBundle.loadString('FontManifest.json')) as List;
    for (final family in manifest.cast<Map>()) {
      await _loadFamily(family['family'] as String, [
        for (final font in (family['fonts'] as List).cast<Map>())
          s.rootBundle.load(font['asset'] as String),
      ]);
    }
  } catch (_) {
    // No bundled fonts.
  }
}

/// A device falls back to its system font for families the app doesn't
/// bundle (e.g. a theme naming a font that isn't installed). The test
/// environment would fall back to a box font instead, so Roboto is
/// registered under those names.
Future<bool> _loadMissingFamilies(r.RenderObject root) async {
  final families = <String>{};
  void visit(r.RenderObject o) {
    if (o is r.RenderParagraph) {
      o.text.visitChildren((span) {
        final family = span.style?.fontFamily;
        if (family != null) families.add(family);
        return true;
      });
      final family = o.text.style?.fontFamily;
      if (family != null) families.add(family);
    }
    o.visitChildren(visit);
  }

  visit(root);
  final missing = families.difference(_loadedFamilies);
  for (final family in missing) {
    await _loadFamily(family, _robotoFiles.map((b) => Future.value(ByteData.sublistView(b))));
  }
  return missing.isNotEmpty;
}

// ---------------------------------------------------------------------------
// Recording the render tree.
// ---------------------------------------------------------------------------

String? _hex(ui.Color? c) =>
    c == null ? null : '#${c.toARGB32().toRadixString(16).padLeft(8, '0')}';

List<double> _rect(ui.Rect r) => [r.left, r.top, r.width, r.height];

/// Paints one render object without its children, recording the children
/// it would have painted, in paint order. Layer contexts it opens (clips,
/// opacity, transforms) are recording contexts too, so no child ever paints.
class _AloneContext extends r.PaintingContext {
  _AloneContext(super.containerLayer, super.estimatedBounds, this.painted, [this.root]);

  final List<r.RenderObject> painted;

  /// The top-level layer of the replay, and how many of its children were
  /// painted before the first child: what comes after is painted on top of
  /// the children (outlines, borders).
  final r.ContainerLayer? root;
  int? layersBeforeChildren;

  @override
  void paintChild(r.RenderObject child, ui.Offset offset) {
    if (painted.isEmpty) {
      stopRecordingIfNeeded();
      var count = 0;
      for (var l = root?.firstChild; l != null; l = l.nextSibling) {
        count++;
      }
      layersBeforeChildren = count;
    }
    painted.add(child);
  }

  @override
  r.PaintingContext createChildContext(r.ContainerLayer childLayer, ui.Rect bounds) =>
      _AloneContext(childLayer, bounds, painted, root);

  void finish() => stopRecordingIfNeeded();
}

class _Recorder {
  _Recorder(this.screenshot);

  final ui.Image screenshot;
  final images = <String, Uint8List>{};
  final _pending = <String, Future<ui.Image?>>{};

  /// Ids whose images may be fully transparent (painted by code we don't
  /// know): those are dropped.
  final _maybeEmpty = <String>{};
  final _imageIds = <ui.Image, String>{};

  String _id() => 'img${_pending.length}';

  String _encode(ui.Image image) => _imageIds.putIfAbsent(image, () {
    final id = _id();
    const limit = 4096; // Figma's largest image side.
    final scale = limit / (image.width > image.height ? image.width : image.height);
    if (scale >= 1) {
      _pending[id] = Future.value(image);
    } else {
      final w = (image.width * scale).floor(), h = (image.height * scale).floor();
      final recorder = ui.PictureRecorder();
      ui.Canvas(recorder).drawImageRect(
        image,
        ui.Rect.fromLTWH(0, 0, image.width.toDouble(), image.height.toDouble()),
        ui.Rect.fromLTWH(0, 0, w.toDouble(), h.toDouble()),
        ui.Paint()..filterQuality = ui.FilterQuality.medium,
      );
      _pending[id] = recorder.endRecording().toImage(w, h);
    }
    return id;
  });

  /// Runs [painter] alone into an image of [size].
  String? _paint(f.CustomPainter painter, ui.Size size) {
    if (size.isEmpty) return null;
    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(recorder)..scale(_scale);
    try {
      painter.paint(canvas, size);
    } catch (_) {
      return null;
    }
    final picture = recorder.endRecording();
    final id = _id();
    _maybeEmpty.add(id);
    _pending[id] = picture.toImage((size.width * _scale).ceil(), (size.height * _scale).ceil());
    return id;
  }

  /// What [o] paints itself, without its children: the part painted
  /// before its children, and the part painted after (on top of them).
  (String?, String?) _paintAlone(r.RenderBox o) {
    if (o.size.isEmpty) return (null, null);
    final layer = r.OffsetLayer();
    final bounds = ui.Offset.zero & o.size;
    final _AloneContext context;
    try {
      context = _AloneContext(layer, bounds, [], layer);
      o.paint(context, ui.Offset.zero);
      context.finish();
    } catch (_) {
      return (null, null);
    }
    final split = context.layersBeforeChildren;
    final front = r.OffsetLayer();
    if (split != null) {
      // Move the layers painted after the first child to their own image.
      final after = <r.Layer>[];
      var i = 0;
      for (var l = layer.firstChild; l != null; l = l.nextSibling) {
        if (i++ >= split) after.add(l);
      }
      for (final l in after) {
        // A handle keeps the layer alive while it has no parent.
        final handle = r.LayerHandle<r.Layer>(l);
        l.remove();
        front.append(l);
        handle.layer = null;
      }
    }
    String? image(r.OffsetLayer l) {
      if (l.firstChild == null) return null;
      final id = _id();
      _maybeEmpty.add(id);
      _pending[id] = l.toImage(bounds, pixelRatio: _scale);
      return id;
    }

    return (image(layer), image(front));
  }

  /// A region of the screenshot.
  String? _crop(ui.Rect rect) {
    final area = rect.intersect(ui.Offset.zero & ui.Size(_width.toDouble(), _height.toDouble()));
    if (area.isEmpty) return null;
    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(recorder);
    canvas.drawImageRect(
      screenshot,
      ui.Rect.fromLTWH(area.left * _scale, area.top * _scale, area.width * _scale, area.height * _scale),
      ui.Rect.fromLTWH(0, 0, area.width * _scale, area.height * _scale),
      ui.Paint(),
    );
    final id = _id();
    _pending[id] = recorder.endRecording().toImage((area.width * _scale).ceil(), (area.height * _scale).ceil());
    return id;
  }

  /// Decoration images come from an ImageProvider, resolved again here.
  String? _provider(f.ImageProvider provider) {
    final id = _id();
    final completer = Completer<ui.Image?>();
    final stream = provider.resolve(f.ImageConfiguration.empty);
    late final f.ImageStreamListener listener;
    listener = f.ImageStreamListener(
      (info, _) {
        stream.removeListener(listener);
        if (!completer.isCompleted) completer.complete(info.image);
      },
      onError: (_, __) {
        stream.removeListener(listener);
        if (!completer.isCompleted) completer.complete(null);
      },
    );
    stream.addListener(listener);
    _pending[id] = completer.future.timeout(const Duration(seconds: 5), onTimeout: () => null);
    return id;
  }

  Future<void> finish() async {
    for (final MapEntry(:key, :value) in _pending.entries) {
      final image = await value;
      if (image == null) continue;
      if (_maybeEmpty.contains(key)) {
        final rgba = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
        if (rgba == null) continue;
        var visible = false;
        final bytes = rgba.buffer.asUint8List();
        for (var i = 3; i < bytes.length; i += 4) {
          if (bytes[i] != 0) {
            visible = true;
            break;
          }
        }
        if (!visible) continue;
      }
      final png = await image.toByteData(format: ui.ImageByteFormat.png);
      if (png != null) images[key] = png.buffer.asUint8List();
    }
    _pending.clear();
  }

  /// Drops nodes whose image turned out empty, and groups left empty.
  List<Map<String, Object?>> prune(List<Map<String, Object?>> nodes) => [
    for (final n in nodes)
      if (n['type'] == 'image' && !images.containsKey(n['image']))
        ...const <Map<String, Object?>>[]
      else if (n['children'] case final List<Map<String, Object?>> kids)
        ...(() {
          final kept = prune(kids);
          if (kept.isEmpty && n['type'] == 'group') return const <Map<String, Object?>>[];
          return [{...n, 'children': kept}];
        })()
      else if (n['type'] == 'box' && n['image'] != null && !images.containsKey(n['image']))
        {...n, 'image': null}
      else
        n,
  ];

  /// The `Ink` widget that [o] is the topmost render object of: its
  /// decoration is painted on the Material below, not by [o].
  f.Ink? _ink(r.RenderObject o) {
    final creator = o.debugCreator;
    if (creator is! f.DebugCreator) return null;
    f.Ink? ink;
    var depth = 0;
    creator.element.visitAncestorElements((e) {
      if (e.widget is f.Ink && identical(e.renderObject, o)) ink = e.widget as f.Ink;
      return ink == null && ++depth < 6;
    });
    return ink;
  }

  String _creator(r.RenderObject o) {
    final creator = o.debugCreator;
    if (creator is f.DebugCreator) {
      return creator.element.widget.runtimeType.toString().split('<').first;
    }
    return o.runtimeType.toString();
  }

  bool _createdBy<T>(r.RenderObject o) {
    final creator = o.debugCreator;
    if (creator is! f.DebugCreator) return false;
    var found = false;
    var depth = 0;
    creator.element.visitAncestorElements((e) {
      if (e.widget is T) found = true;
      return !found && ++depth < 4;
    });
    return found || creator.element.widget is T;
  }

  ui.Rect _bounds(r.RenderBox box) =>
      r.MatrixUtils.transformRect(box.getTransformTo(null), ui.Offset.zero & box.size);

  final _paintOrder = <r.RenderObject, List<r.RenderObject>>{};

  /// The children [o] paints, in the order it paints them: offstage routes
  /// and widgets, and hidden IndexedStack children, are left out, and a
  /// text field's background comes before its text even though it is its
  /// last child. Found by replaying [o]'s paint into a recording context.
  List<r.RenderObject> _paintedChildren(r.RenderObject o) => _paintOrder.putIfAbsent(o, () {
    final painted = <r.RenderObject>[];
    final layer = r.OffsetLayer();
    try {
      final context = _AloneContext(layer, o.paintBounds, painted, layer);
      o.paint(context, ui.Offset.zero);
      context.finish();
    } catch (_) {
      painted.clear();
      if (!(o is r.RenderOffstage && o.offstage)) o.visitChildren(painted.add);
    }
    final seen = <r.RenderObject>{};
    return [for (final c in painted) if (seen.add(c)) c];
  });

  List<Map<String, Object?>> children(r.RenderObject o) => [
    for (final c in _paintedChildren(o)) ...record(c),
  ];

  static const _silent = {
    'RenderConstrainedBox', 'RenderLimitedBox', 'RenderPadding', 'RenderPositionedBox',
    'RenderAspectRatio', 'RenderFlex', 'RenderStack', 'RenderIndexedStack',
    'RenderSizedOverflowBox', 'RenderFractionallySizedOverflowBox', 'RenderConstrainedOverflowBox',
    'RenderPointerListener', 'RenderMouseRegion', 'RenderIgnorePointer', 'RenderAbsorbPointer',
    'RenderSemanticsAnnotations', 'RenderMergeSemantics', 'RenderExcludeSemantics',
    'RenderBlockSemantics', 'RenderIndexedSemantics', 'RenderSemanticsGestureHandler',
    'RenderRepaintBoundary', 'RenderOffstage', 'RenderMetaData', 'RenderErrorBox',
    'RenderFractionalTranslation', 'RenderTransform', 'RenderCustomMultiChildLayoutBox',
    'RenderCustomSingleChildLayoutBox', 'RenderWrap', 'RenderListBody', 'RenderTable',
    'RenderIntrinsicWidth', 'RenderIntrinsicHeight', 'RenderBaseline', 'RenderFlow',
    'RenderAnimatedSize', 'RenderAnimatedOpacity', 'RenderOpacity', 'RenderSliverToBoxAdapter',
    '_RenderInkFeatures', '_RenderColoredBox', 'RenderDecoratedBox', 'RenderPhysicalModel',
    'RenderPhysicalShape', 'RenderClipRect', 'RenderClipRRect', 'RenderClipOval', 'RenderClipPath',
    'RenderParagraph', 'RenderImage', 'RenderCustomPaint', 'RenderEditable',
  };

  /// Containers known to paint nothing themselves (or only ink splashes).
  static const _noPaint = {
    '_RenderInkFeatures', '_RenderTheater', 'RenderView', '_ReusableRenderView',
    'RenderAnnotatedRegion<SystemUiOverlayStyle>', '_RenderLayoutSurrogateProxyBox',
    '_RenderExclusiveMouseRegion', 'RenderTapRegionSurface', 'RenderTapRegion',
    '_RenderInputPadding', '_RenderChipRedirectingHitDetection', 'RenderProxyBox',
    'RenderFocusTrap', '_RenderFocusTrap', 'RenderSliverPadding',
  };

  List<Map<String, Object?>> record(r.RenderObject o) {
    if (o is! r.RenderBox) {
      // Slivers and views: record their box descendants.
      return children(o);
    }
    if (!o.hasSize || o.size.isEmpty && o is! r.RenderParagraph) {
      return o.hasSize ? const [] : children(o);
    }
    final rect = _bounds(o);
    final name = _creator(o);
    Map<String, Object?> node(String type, [Map<String, Object?> props = const {}]) => {
      'type': type,
      'name': name,
      'rect': _rect(rect),
      ...props,
    };

    // Opacity and clips wrap their content.
    if (o is r.RenderOpacity || o is r.RenderAnimatedOpacity) {
      final opacity = o is r.RenderOpacity ? o.opacity : (o as r.RenderAnimatedOpacity).opacity.value;
      if (opacity == 0) return const [];
      if (opacity == 1) return children(o);
      return [node('group', {'opacity': opacity, 'children': children(o)})];
    }
    if (o is r.RenderClipRect || o is r.RenderClipRRect || o is r.RenderClipOval || o is r.RenderClipPath) {
      double? radius;
      if (o is r.RenderClipRRect) {
        final br = o.borderRadius.resolve(ui.TextDirection.ltr);
        radius = br.topLeft.x;
      } else if (o is r.RenderClipOval) {
        radius = o.size.shortestSide / 2;
      }
      return [node('group', {'clip': true, 'radius': radius, 'children': children(o)})];
    }

    if (o is r.RenderParagraph) return [_text(o, node)];
    if (o is r.RenderEditable) {
      return [node('text', _textProps(o.text ?? const f.TextSpan(), o.textAlign, o.maxLines))];
    }
    if (o is r.RenderImage) {
      final image = o.image;
      if (image == null) return const [];
      return [node('image', {'image': _encode(image), 'fit': o.fit?.name ?? 'scaleDown'})];
    }
    if (o is r.RenderCustomPaint) {
      final back = o.painter == null ? null : _paint(o.painter!, o.size);
      final front = o.foregroundPainter == null || o.foregroundPainter.runtimeType.toString().contains('Scrollbar')
          ? null
          : _paint(o.foregroundPainter!, o.size);
      final inner = children(o);
      if (back == null && front == null) return inner;
      return [
        node('group', {
          'children': [
            if (back != null) node('image', {'image': back, 'fit': 'fill', 'name': '${name} painter'}),
            ...inner,
            if (front != null) node('image', {'image': front, 'fit': 'fill', 'name': '${name} painter'}),
          ],
        }),
      ];
    }
    if (o is r.RenderDecoratedBox) {
      final props = _decoration(o.decoration, o.size);
      if (props == null) return children(o);
      return [node('box', {...props, 'children': children(o)})];
    }
    if (o is r.RenderPhysicalModel) {
      return [
        node('box', {
          'fill': _hex(o.color),
          'elevation': o.elevation,
          'shadowColor': _hex(o.shadowColor),
          'radius': o.shape == f.BoxShape.circle
              ? o.size.shortestSide / 2
              : o.borderRadius?.resolve(ui.TextDirection.ltr).topLeft.x,
          'clip': o.clipBehavior != ui.Clip.none,
          'children': children(o),
        }),
      ];
    }
    if (o is r.RenderPhysicalShape) {
      final clipper = o.clipper;
      final shape = clipper is f.ShapeBorderClipper ? _shape(clipper.shape, o.size) : const <String, Object?>{};
      return [
        node('box', {
          'fill': _hex(o.color),
          'elevation': o.elevation,
          'shadowColor': _hex(o.shadowColor),
          ...shape,
          'clip': o.clipBehavior != ui.Clip.none,
          'children': children(o),
        }),
      ];
    }
    if (o.runtimeType.toString() == '_RenderColoredBox') {
      final creator = o.debugCreator;
      final widget = creator is f.DebugCreator ? creator.element.widget : null;
      if (widget is f.ColoredBox) {
        return [node('box', {'fill': _hex(widget.color), 'children': children(o)})];
      }
    }

    final ink = _ink(o);
    final inkDecoration = ink?.decoration;
    if (inkDecoration != null) {
      final props = _decoration(inkDecoration, o.size);
      if (props != null) return [node('box', {...props, 'children': children(o)})];
    }

    final inner = children(o);
    final type = o.runtimeType.toString();
    final isLeaf = inner.isEmpty && _paintedChildren(o).isEmpty;
    if (!isLeaf && !_silent.contains(type) && !_noPaint.contains(type)) {
      // A container we don't model may paint too (a chip's checkmark):
      // keep what it paints itself, under its children.
      final (back, front) = _paintAlone(o);
      if (back != null || front != null) {
        return [
          node('group', {
            'children': [
              if (back != null) node('image', {'image': back, 'fit': 'fill', 'crop': type}),
              ...inner,
              if (front != null) node('image', {'image': front, 'fit': 'fill', 'crop': type}),
            ],
          }),
        ];
      }
    }
    if (isLeaf && !_silent.contains(type)) {
      // Something we don't model paints here: keep its pixels.
      final id = _crop(rect);
      if (id != null) return [node('image', {'image': id, 'fit': 'fill', 'crop': type})];
    }
    if (o is r.RenderFlex && inner.length > 1) {
      return [node('group', {'flex': o.direction.name, 'children': inner})];
    }
    return inner;
  }

  Map<String, Object?> _text(r.RenderParagraph o, Map<String, Object?> Function(String, [Map<String, Object?>]) node) {
    final style = _style(o.text);
    final family = style?.fontFamily ?? '';
    final plain = o.text.toPlainText();
    final isIcon = family == 'MaterialIcons' || family.endsWith('CupertinoIcons');
    if (isIcon && plain.runes.length == 1) {
      return node('icon', {
        'family': family.endsWith('CupertinoIcons') ? 'CupertinoIcons' : family,
        'codePoint': plain.runes.first,
        'size': style?.fontSize,
        'color': _hex(style?.color),
      });
    }
    if (_createdBy<f.Icon>(o)) {
      // An icon from a font Figma won't have: keep its pixels.
      final id = _crop(_bounds(o));
      if (id != null) return node('image', {'image': id, 'fit': 'fill'});
    }
    return node('text', _textProps(o.text, o.textAlign, o.maxLines));
  }

  f.TextStyle? _style(f.InlineSpan span) {
    var style = span.style;
    f.TextStyle? first;
    span.visitChildren((child) {
      if (identical(child, span)) return true;
      first ??= child.style;
      return first == null;
    });
    if (first != null) style = style?.merge(first) ?? first;
    return style;
  }

  Map<String, Object?> _textProps(f.InlineSpan span, ui.TextAlign align, int? maxLines) {
    final style = _style(span);
    return {
      'text': span.toPlainText(),
      'style': {
        'family': style?.fontFamily,
        'size': style?.fontSize,
        'weight': style?.fontWeight?.value,
        'italic': style?.fontStyle == ui.FontStyle.italic,
        'color': _hex(style?.color ?? style?.foreground?.color),
        'height': style?.height,
        'letterSpacing': style?.letterSpacing,
        'decoration': style?.decoration?.toString(),
      },
      'align': align.name,
      'maxLines': maxLines,
    };
  }

  Map<String, Object?>? _decoration(f.Decoration decoration, ui.Size size) {
    if (decoration is f.BoxDecoration) {
      final border = decoration.border;
      Map<String, Object?>? stroke;
      if (border is f.Border && border.isUniform && border.top.style != f.BorderStyle.none) {
        stroke = {'color': _hex(border.top.color), 'width': border.top.width};
      } else if (border is f.Border && border.bottom.style != f.BorderStyle.none && border.bottom.width > 0) {
        // A divider-like bottom border.
        stroke = {'color': _hex(border.bottom.color), 'width': border.bottom.width, 'side': 'bottom'};
      } else if (border is f.Border && border.top.style != f.BorderStyle.none && border.top.width > 0) {
        stroke = {'color': _hex(border.top.color), 'width': border.top.width, 'side': 'top'};
      }
      final gradient = decoration.gradient;
      final image = decoration.image;
      final radius = decoration.shape == f.BoxShape.circle
          ? size.shortestSide / 2
          : decoration.borderRadius?.resolve(ui.TextDirection.ltr).topLeft.x;
      return {
        'fill': _hex(decoration.color),
        if (gradient != null) 'gradient': _gradient(gradient),
        'radius': radius,
        'stroke': stroke,
        'shadows': [
          for (final b in decoration.boxShadow ?? const <f.BoxShadow>[])
            {'color': _hex(b.color), 'x': b.offset.dx, 'y': b.offset.dy, 'blur': b.blurRadius, 'spread': b.spreadRadius},
        ],
        if (image != null) 'image': _provider(image.image),
        if (image != null) 'fit': image.fit?.name ?? 'scaleDown',
      };
    }
    if (decoration is f.ShapeDecoration) {
      return {
        'fill': _hex(decoration.color),
        ..._shape(decoration.shape, size),
        'shadows': [
          for (final b in decoration.shadows ?? const <f.BoxShadow>[])
            {'color': _hex(b.color), 'x': b.offset.dx, 'y': b.offset.dy, 'blur': b.blurRadius, 'spread': b.spreadRadius},
        ],
      };
    }
    return null;
  }

  Map<String, Object?> _gradient(f.Gradient g) {
    List<double> point(f.AlignmentGeometry a) {
      final r = a.resolve(ui.TextDirection.ltr);
      return [(r.x + 1) / 2, (r.y + 1) / 2];
    }

    return {
      'type': g is f.RadialGradient ? 'radial' : 'linear',
      'colors': [for (final c in g.colors) _hex(c)],
      'stops': g.stops,
      if (g is f.LinearGradient) 'begin': point(g.begin),
      if (g is f.LinearGradient) 'end': point(g.end),
      if (g is f.RadialGradient) 'center': point(g.center),
      if (g is f.RadialGradient) 'radius': g.radius,
    };
  }

  Map<String, Object?> _shape(f.ShapeBorder shape, ui.Size size) {
    double? radius;
    f.BorderSide? side;
    if (shape is f.RoundedRectangleBorder) {
      radius = shape.borderRadius.resolve(ui.TextDirection.ltr).topLeft.x;
      side = shape.side;
    } else if (shape is f.StadiumBorder) {
      radius = size.shortestSide / 2;
      side = shape.side;
    } else if (shape is f.CircleBorder) {
      radius = size.shortestSide / 2;
      side = shape.side;
    } else if (shape is f.ContinuousRectangleBorder) {
      radius = shape.borderRadius.resolve(ui.TextDirection.ltr).topLeft.x / 2;
      side = shape.side;
    } else if (shape is f.OutlinedBorder) {
      side = shape.side;
    }
    return {
      'radius': radius,
      if (side != null && side.style != f.BorderStyle.none && side.width > 0)
        'stroke': {'color': _hex(side.color), 'width': side.width},
    };
  }
}

Map<String, Object?> _theme(f.ThemeData d) {
  final s = d.colorScheme;
  final t = d.textTheme;
  f.TextStyle? style(f.TextStyle? x) => x;
  Map<String, Object?> text(f.TextStyle? x) => {
    'family': x?.fontFamily,
    'size': x?.fontSize,
    'weight': x?.fontWeight?.value,
    'height': x?.height,
    'letterSpacing': x?.letterSpacing,
  };
  return {
    'brightness': s.brightness.name,
    'colorScheme': {
      'primary': _hex(s.primary), 'onPrimary': _hex(s.onPrimary),
      'primaryContainer': _hex(s.primaryContainer), 'onPrimaryContainer': _hex(s.onPrimaryContainer),
      'secondary': _hex(s.secondary), 'onSecondary': _hex(s.onSecondary),
      'secondaryContainer': _hex(s.secondaryContainer), 'onSecondaryContainer': _hex(s.onSecondaryContainer),
      'tertiary': _hex(s.tertiary), 'onTertiary': _hex(s.onTertiary),
      'tertiaryContainer': _hex(s.tertiaryContainer), 'onTertiaryContainer': _hex(s.onTertiaryContainer),
      'error': _hex(s.error), 'onError': _hex(s.onError),
      'errorContainer': _hex(s.errorContainer), 'onErrorContainer': _hex(s.onErrorContainer),
      'surface': _hex(s.surface), 'onSurface': _hex(s.onSurface),
      'surfaceDim': _hex(s.surfaceDim), 'surfaceBright': _hex(s.surfaceBright),
      'surfaceContainerLowest': _hex(s.surfaceContainerLowest),
      'surfaceContainerLow': _hex(s.surfaceContainerLow),
      'surfaceContainer': _hex(s.surfaceContainer),
      'surfaceContainerHigh': _hex(s.surfaceContainerHigh),
      'surfaceContainerHighest': _hex(s.surfaceContainerHighest),
      'onSurfaceVariant': _hex(s.onSurfaceVariant),
      'outline': _hex(s.outline), 'outlineVariant': _hex(s.outlineVariant),
      'shadow': _hex(s.shadow), 'scrim': _hex(s.scrim),
      'inverseSurface': _hex(s.inverseSurface), 'onInverseSurface': _hex(s.onInverseSurface),
      'inversePrimary': _hex(s.inversePrimary), 'surfaceTint': _hex(s.surfaceTint),
    },
    'textTheme': {
      'displayLarge': text(style(t.displayLarge)), 'displayMedium': text(t.displayMedium),
      'displaySmall': text(t.displaySmall), 'headlineLarge': text(t.headlineLarge),
      'headlineMedium': text(t.headlineMedium), 'headlineSmall': text(t.headlineSmall),
      'titleLarge': text(t.titleLarge), 'titleMedium': text(t.titleMedium),
      'titleSmall': text(t.titleSmall), 'bodyLarge': text(t.bodyLarge),
      'bodyMedium': text(t.bodyMedium), 'bodySmall': text(t.bodySmall),
      'labelLarge': text(t.labelLarge), 'labelMedium': text(t.labelMedium),
      'labelSmall': text(t.labelSmall),
    },
  };
}

// ---------------------------------------------------------------------------
// The capture.
// ---------------------------------------------------------------------------

Future<void> _settle(t.WidgetTester tester) async {
  // Not pumpAndSettle: progress indicators animate forever.
  await tester.pump();
  for (var i = 0; i < 10; i++) {
    await tester.pump(const Duration(milliseconds: 100));
  }
}

/// Images decode asynchronously, which the test's fake clock never
/// finishes: decode them in real time, then rebuild.
Future<void> _decodeImages(t.WidgetTester tester) async {
  final images = t.find.byType(f.Image).evaluate().toList();
  if (images.isEmpty) return;
  await tester.runAsync(() async {
    for (final element in images) {
      final widget = element.widget as f.Image;
      try {
        await f.precacheImage(widget.image, element).timeout(const Duration(seconds: 5));
      } catch (_) {
        // Network images fail in tests; they stay empty.
      }
    }
  });
  await _settle(tester);
}

String _describe(Object error, [StackTrace? stack]) {
  var text = error.toString().split('\n').firstWhere((l) => l.trim().isNotEmpty, orElse: () => '$error');
  if (text.length > 300) text = '${text.substring(0, 300)}…';
  // Where in the harness it failed, for errors that are ours.
  final frame = stack?.toString().split('\n').where((l) => l.contains('capture_test.dart')).firstOrNull;
  return frame == null ? text : '$text [${frame.replaceAll(RegExp(r'\s+'), ' ').trim()}]';
}

void main() {
  t.testWidgets('flutter2figma capture', (tester) async {
    tester.view.physicalSize = ui.Size(_width.toDouble(), _height.toDouble());
    tester.view.devicePixelRatio = 1;
    f.WidgetsApp.debugAllowBannerOverride = false;
    final result = <String, Object?>{
      'screens': <Object?>[],
      'errors': <String>[],
      'warnings': <String>[],
    };
    final errors = result['errors'] as List<String>;
    final warnings = result['warnings'] as List<String>;

    // Flutter's errors, per screen. Layout overflows are the app's own
    // (reported, the screen is still exported); anything else means the
    // screen didn't build.
    var current = 'main()';
    final failures = <String>[];
    final originalOnError = f.FlutterError.onError;
    f.FlutterError.onError = (details) {
      final message = details.exceptionAsString().split('\n').first.trim();
      final where = RegExp(r'/(lib/[^\s:]+\.dart:\d+)').firstMatch(details.toString())?.group(1);
      final text = '$current: $message${where == null ? '' : ' ($where)'}';
      if (message.contains('overflowed')) {
        if (!warnings.contains(text)) warnings.add(text);
      } else {
        failures.add(text);
      }
    };
    addTearDown(() => f.FlutterError.onError = originalOnError);
    void save() => File(_out).writeAsStringSync(jsonEncode(result));
    save();

    await tester.runAsync(_loadFonts);
    try {
      await tester.runAsync(_setUp);
    } catch (e) {
      errors.add('setUp: ${_describe(e)}');
    }

    // Start the app through its own main().
    // In real time (runAsync), so plugin calls and timers in main() resolve.
    try {
      await tester.runAsync(() async {
        final started = (app.main as dynamic)();
        if (started is Future) await started.timeout(const Duration(seconds: 10));
      });
    } catch (e) {
      errors.add('main(): ${_describe(e)}');
    }
    // runApp may come later than main() returns (after a `.then` on a
    // platform call, ...): let real time pass until a Navigator exists.
    final navigators = t.find.byType(f.Navigator);
    for (var i = 0; i < 25 && navigators.evaluate().isEmpty; i++) {
      await tester.runAsync(() => Future<void>.delayed(const Duration(milliseconds: 200)));
      await _settle(tester);
    }
    final startup = tester.takeException();
    if (startup != null) errors.add('main(): ${_describe(startup)}');
    errors.addAll(failures);
    failures.clear();

    if (navigators.evaluate().isEmpty) {
      errors.add('The app has no Navigator to push screens onto');
      save();
      return;
    }
    final view = tester.binding.renderViews.first;

    /// Records what is on screen now as [name].
    Future<void> record(String name) async {
      final loaded = await tester.runAsync(() => _loadMissingFamilies(view));
      if (loaded == true) await _settle(tester);
      // Images are encoded in real time: their futures would never
      // complete in the test's fake-async zone.
      Object? failure;
      StackTrace? failureStack;
      final captured = await tester.runAsync(() async {
       try {
        final layer = view.debugLayer! as r.OffsetLayer;
        final screenshot = await layer.toImage(view.paintBounds, pixelRatio: _scale);
        if (_shots.isNotEmpty) {
          final png = await screenshot.toByteData(format: ui.ImageByteFormat.png);
          File('$_shots/$name.png')
            ..createSync(recursive: true)
            ..writeAsBytesSync(png!.buffer.asUint8List());
        }
        final recorder = _Recorder(screenshot);
        final tree = recorder.children(view);
        await recorder.finish().timeout(const Duration(seconds: 60));
        return (recorder.prune(tree), recorder);
       } catch (e, stack) {
        failure = e;
        failureStack = stack;
        return null;
       }
      });
      if (captured == null) {
        throw StateError(_describe(failure ?? 'recording failed', failureStack));
      }
      final (tree, recorder) = captured;
      final context = tester.element(t.find.byType(f.Navigator).first);
      (result['screens'] as List).add({
        'name': name,
        'width': _width,
        'height': _height,
        'theme': _theme(f.Theme.of(context)),
        'tree': tree,
        'images': {
          for (final MapEntry(:key, :value) in recorder.images.entries) key: base64Encode(value),
        },
      });
      save();
    }

    // The screen the app starts on, exactly as the app shows it.
    final done = <String>{};
    await _decodeImages(tester);
    for (final name in _screens.keys) {
      final shown = t.find.byWidgetPredicate((w) => w.runtimeType.toString() == name);
      if (shown.evaluate().isEmpty) continue;
      current = name;
      try {
        await record(name);
        done.add(name);
      } catch (e, stack) {
        errors.add('$name: ${_describe(e, stack)}');
      }
      break;
    }
    final providers = _routeProviders();

    for (final MapEntry(key: name, value: build) in _screens.entries) {
      if (done.contains(name)) continue;
      current = name;
      failures.clear();
      final navigator = tester.state<f.NavigatorState>(navigators.first);
      try {
        // Replace the whole stack, as if the screen were the app's first:
        // no back button that the real screen wouldn't show.
        navigator.pushAndRemoveUntil(
          f.PageRouteBuilder<void>(
            pageBuilder: (_, __, ___) => _provide(providers, _wrap(name, _build(name, build))),
            transitionDuration: Duration.zero,
            reverseTransitionDuration: Duration.zero,
          ),
          (_) => false,
        );
        await _settle(tester);
        await _decodeImages(tester);
        final failure = tester.takeException();
        if (failure != null || failures.isNotEmpty) {
          errors.add(failures.isNotEmpty ? failures.first : '$name: ${_describe(failure!)}');
          continue;
        }
        await record(name);
      } catch (e, stack) {
        errors.add('$name: ${_describe(e, stack)}');
        tester.takeException();
      }
    }
    save();
  }, timeout: const t.Timeout(Duration(minutes: 10)));
}
''';
